# Generated by Django 5.0 on 2023-12-11 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kpi_1', models.DecimalField(decimal_places=10, max_digits=19)),
                ('kpi_2', models.DecimalField(decimal_places=10, max_digits=19)),
                ('kpi_3', models.DecimalField(decimal_places=10, max_digits=19)),
                ('kpi_4', models.DecimalField(decimal_places=10, max_digits=19)),
                ('kpi_5', models.DecimalField(decimal_places=10, max_digits=19)),
                ('kpi_6', models.DecimalField(decimal_places=10, max_digits=19)),
                ('kpi_7', models.DecimalField(decimal_places=10, max_digits=19)),
                ('kpi_8', models.DecimalField(decimal_places=10, max_digits=19)),
                ('kpi_9', models.DecimalField(decimal_places=10, max_digits=19)),
                ('kpi_10', models.DecimalField(decimal_places=10, max_digits=19)),
                ('kpi_11', models.DecimalField(decimal_places=10, max_digits=19)),
                ('kpi_12', models.DecimalField(decimal_places=10, max_digits=19)),
                ('kpi_13', models.DecimalField(decimal_places=10, max_digits=19)),
                ('kpi_14', models.DecimalField(decimal_places=10, max_digits=19)),
                ('kpi_15', models.DecimalField(decimal_places=10, max_digits=19)),
                ('kpi_16', models.DecimalField(decimal_places=10, max_digits=19)),
                ('kpi_17', models.DecimalField(decimal_places=10, max_digits=19)),
                ('kpi_18', models.DecimalField(decimal_places=10, max_digits=19)),
                ('kpi_19', models.DecimalField(decimal_places=10, max_digits=19)),
                ('kpi_20', models.DecimalField(decimal_places=10, max_digits=19)),
                ('city', models.CharField(max_length=25)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Province',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kpi_1', models.DecimalField(decimal_places=10, max_digits=19)),
                ('kpi_2', models.DecimalField(decimal_places=10, max_digits=19)),
                ('kpi_3', models.DecimalField(decimal_places=10, max_digits=19)),
                ('kpi_4', models.DecimalField(decimal_places=10, max_digits=19)),
                ('kpi_5', models.DecimalField(decimal_places=10, max_digits=19)),
                ('kpi_6', models.DecimalField(decimal_places=10, max_digits=19)),
                ('kpi_7', models.DecimalField(decimal_places=10, max_digits=19)),
                ('kpi_8', models.DecimalField(decimal_places=10, max_digits=19)),
                ('kpi_9', models.DecimalField(decimal_places=10, max_digits=19)),
                ('kpi_10', models.DecimalField(decimal_places=10, max_digits=19)),
                ('kpi_11', models.DecimalField(decimal_places=10, max_digits=19)),
                ('kpi_12', models.DecimalField(decimal_places=10, max_digits=19)),
                ('kpi_13', models.DecimalField(decimal_places=10, max_digits=19)),
                ('kpi_14', models.DecimalField(decimal_places=10, max_digits=19)),
                ('kpi_15', models.DecimalField(decimal_places=10, max_digits=19)),
                ('kpi_16', models.DecimalField(decimal_places=10, max_digits=19)),
                ('kpi_17', models.DecimalField(decimal_places=10, max_digits=19)),
                ('kpi_18', models.DecimalField(decimal_places=10, max_digits=19)),
                ('kpi_19', models.DecimalField(decimal_places=10, max_digits=19)),
                ('kpi_20', models.DecimalField(decimal_places=10, max_digits=19)),
                ('province', models.CharField(max_length=25)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kpi_1', models.DecimalField(decimal_places=10, max_digits=19)),
                ('kpi_2', models.DecimalField(decimal_places=10, max_digits=19)),
                ('kpi_3', models.DecimalField(decimal_places=10, max_digits=19)),
                ('kpi_4', models.DecimalField(decimal_places=10, max_digits=19)),
                ('kpi_5', models.DecimalField(decimal_places=10, max_digits=19)),
                ('kpi_6', models.DecimalField(decimal_places=10, max_digits=19)),
                ('kpi_7', models.DecimalField(decimal_places=10, max_digits=19)),
                ('kpi_8', models.DecimalField(decimal_places=10, max_digits=19)),
                ('kpi_9', models.DecimalField(decimal_places=10, max_digits=19)),
                ('kpi_10', models.DecimalField(decimal_places=10, max_digits=19)),
                ('kpi_11', models.DecimalField(decimal_places=10, max_digits=19)),
                ('kpi_12', models.DecimalField(decimal_places=10, max_digits=19)),
                ('kpi_13', models.DecimalField(decimal_places=10, max_digits=19)),
                ('kpi_14', models.DecimalField(decimal_places=10, max_digits=19)),
                ('kpi_15', models.DecimalField(decimal_places=10, max_digits=19)),
                ('kpi_16', models.DecimalField(decimal_places=10, max_digits=19)),
                ('kpi_17', models.DecimalField(decimal_places=10, max_digits=19)),
                ('kpi_18', models.DecimalField(decimal_places=10, max_digits=19)),
                ('kpi_19', models.DecimalField(decimal_places=10, max_digits=19)),
                ('kpi_20', models.DecimalField(decimal_places=10, max_digits=19)),
                ('site', models.CharField(max_length=25)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
