# Generated by Django 5.0 on 2023-12-11 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aggregation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='city',
            field=models.CharField(max_length=25, unique=True),
        ),
        migrations.AlterField(
            model_name='province',
            name='province',
            field=models.CharField(max_length=25, unique=True),
        ),
        migrations.AlterField(
            model_name='site',
            name='site',
            field=models.CharField(max_length=25, unique=True),
        ),
    ]
